// Auto generated by utensor-cli

#ifndef __MODELS_MNIST_FOR_MC_H
#define __MODELS_MNIST_FOR_MC_H
#include "uTensor/core/context.hpp"
void get_mnist_for_mc_ctx(Context& ctx, Tensor* input_0);
#endif // __MODELS_MNIST_FOR_MC_H